# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='cert name')),
                ('cert_path', models.CharField(blank=True, max_length=300, verbose_name='path to certificate')),
                ('key_path', models.CharField(blank=True, max_length=300, verbose_name='path to private kay')),
            ],
        ),
    ]
