# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_path',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='key_path',
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='is revoked'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
