# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='cert name')),
                ('email', models.EmailField(max_length=254, verbose_name='subject email')),
                ('revoked', models.BooleanField(default=False, verbose_name='is revoked')),
            ],
        ),
    ]
