# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_api', '0002_certificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='cert name'),
        ),
    ]
